version: '3.4'
services:
  cms:
    build: .
    container_name: cms
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: 'cms-user'
      SPRING_DATASOURCE_PASSWORD: 'password'
      SPRING_PROFILES_ACTIVE: 'prod'
    depends_on:
      - db
  db:
    image: mysql:8.0.20
    container_name: db
    volumes:
      - group2-cms-db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'cms'
      MYSQL_USER: 'cms-user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
volumes:
  group2-cms-db: