spring:
  application:
    name: Group 2 CMS
  datasource:
    url: jdbc:mysql://localhost:3306/cms
    username: cms-user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    flyway:
      baseline-on-migrate: true
      schemas: cs4230
      user: ${spring.datasource.username}
      url: ${spring.datasource.url}

