
spring:
  application:
    name: Group 2 CMS
  datasource:
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: cms-user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    flyway:
      baseline-on-migrate: true
      schemas: cms
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}
      url: ${spring.datasource.url}
contact:
  defaultName: "Kelton"
