CREATE TABLE USER(
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(512) NOT NULL,
    LOCKED BIT NOT NULL,
    ENABLED BIT NOT NULL,
    CREDENTIALS_EXPIRED_ON datetime NOT NULL,
    EXPIRED_ON datetime NOT NULL,
    CREATED_ON datetime NOT NULL,
    MODIFIED_ON datetime NOT NULL
) ENGINE=INNODB;

CREATE TABLE ROLE
(
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE USER_ROLE
(
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT UNSIGNED NOT NULL,
    ROLE_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
) ENGINE=INNODB;

CREATE TABLE PERMISSION
(
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE ROLE_PERMISSION
(
    RoleToPermissionID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RoleID INT UNSIGNED NOT NULL,
    PermissionID INT UNSIGNED NOT NULL,
    FOREIGN KEY (RoleID) REFERENCES ROLE(ID),
    FOREIGN KEY (PermissionID) REFERENCES PERMISSION(ID)
) ENGINE=INNODB;

CREATE TABLE BLOG_POST
(
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BLOG_TITLE VARCHAR(200) NOT NULL,
    BLOG_BODY longtext NOT NULL,
    CREATED_ON datetime NOT NULL,
    MODIFIED_ON datetime NOT NULL,
    AUTHOR_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID)
) ENGINE=INNODB;

CREATE TABLE BLOG_POST_PERMISSION
(
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BLOG_POST_ID INT UNSIGNED NOT NULL,
    PERMISSION_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (BLOG_POST_ID) REFERENCES BLOG_POST(ID),
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID)
) ENGINE=INNODB;

CREATE TABLE TAG
(
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50)
) ENGINE=INNODB;

CREATE TABLE BLOG_POST_TAG
(
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BLOG_POST_ID INT UNSIGNED NOT NULL,
    TAG_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (BLOG_POST_ID) REFERENCES BLOG_POST(ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
) ENGINE=INNODB;

CREATE TABLE COMMENT
(
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BLOG_POST_ID INT UNSIGNED NOT NULL,
    BODY mediumtext NOT NULL,
    USER_ID INT UNSIGNED NOT NULL,
    CREATED_ON datetime NOT NULL,
    FOREIGN KEY (BLOG_POST_ID) REFERENCES BLOG_POST(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=INNODB;