INSERT INTO Tag (TagName) values ("Sports");
INSERT INTO Tag (TagName) values ("Technology");
INSERT INTO Tag (TagName) values ("Politics");
INSERT INTO Tag (TagName) values ("Music");
INSERT INTO Tag (TagName) values ("Finance");


INSERT INTO Blog (BlogTitle, BlogBody, AuthorID) VALUES ("This is a default Sports blog", "I don't really know what to enter here so I'm just going to keep typing random things until I feel it is long enough. I want to make this post really long so that we can format the page accordingly. I will also create a shorter blog post so we can test to see if that works with short blogs as well. I don't really know what else to type. I'm considering just copying an essay I have written for school so that this blog post is reallllly long.  Here is my essay about John Steinbeck (I Think this was from High school).
 	John Steinbeck was born on February 27, 1902 in Salinas, California. He was the third child of Olive Hamilton and John Ernst Steinbeck. He had two older sisters and a younger sister. Salinas was a farming community, and he wrote about it in 1952 in East of Eden. When John was in his youth his family went through many financial problems including his father losing his jab as manager of Sperry flour and having a grain store they own closed down. These problems continued until John went to college. (Encyclopedia of World Biography)
	When Steinbeck was four years old he received his own pony named Jill. Jill became an inspiration for his future series of stories, The Red Pony. On his ninth birthday his Aunt Mollie gave him a copy of Le Morte d’Arthur.  This book inspired him to write Tortilla Flat which used Arthurian Tropes and chapter headings. He also traveled to England and Wales to research Arthurian legends in preparation for a modernized text of Arthurian tales. (Keith Ferrell, 82)
	During High School John showed strong interest in writing. He would work late into the night up in his attic and write short stories. Sometimes he would invite his friends over and read them aloud. John writes decades later, 'I would send in my little stories out to magazines under a false name and I never put a return address on them… I wonder what I was thinking of? I was scared to death to get a rejection slip, but more, to get an acceptance.' (John Steinbeck Biography) By the age of fourteen he was certain he wanted to become and Author.
	In 1919 he enrolled at Stanford University hoping to sharpen his writing skills. He took world history and creative writing courses, and in 1923 he enrolled in a biology course at Hopkins Marine Station. He left Stanford in 1925 without receiving a degree. (Galegroup)
	Some of Steinbeck’s major works were Of Mice and Men, The Grapes of Wrath, East of Eden, The Pearl, and Canary Row. His writings were very important to us because they shed some light on the Great Depression and the years surrounding it. He also talked a lot about the American Dream and realism. Most of his books were about the Great Depression, but some of his books, like Tortilla Flat, were about Arthurian tales.
	Steinbeck’s book, Of Mice and Men, was inspired by his growing up on a ranch himself. It shows how bad the ranchers lives were during the Great Depression, moving Ranch to Ranch just so they could stay alive. Ranchers barely made any friends because they were constantly moving from place to place. It also talks about the American Dream. In the book George and Lenny’s dream was to own their very own Ranch, so they wouldn’t need to constantly keep moving, and on the ranch they would have all kinds of animals, especially bunnies, for Lenny to play with.
	John Steinbeck died in New York City on December 20, 1968 of Heart disease and congestive heart failure. He had been a lifelong smoker, and his autopsy showed nearly complete occlusion of the main coronary arteries. He died at the age of 66, and according to his wishes, he was cremated and interred at the Hamilton Family Gravesite in Salinas.", 6);
INSERT INTO Blog (BlogTitle, BlogBody, AuthorID) VALUES ("This is a default Technology blog", "I don't really know what to enter here so I'm just going to keep typing random things until I feel it is long enough. I want to make this post really long so that we can format the page accordingly. I will also create a shorter blog post so we can test to see if that works with short blogs as well. I don't really know what else to type. I'm considering just copying an essay I have written for school so that this blog post is reallllly long.  Here is my essay about John Steinbeck (I Think this was from High school).
 	John Steinbeck was born on February 27, 1902 in Salinas, California. He was the third child of Olive Hamilton and John Ernst Steinbeck. He had two older sisters and a younger sister. Salinas was a farming community, and he wrote about it in 1952 in East of Eden. When John was in his youth his family went through many financial problems including his father losing his jab as manager of Sperry flour and having a grain store they own closed down. These problems continued until John went to college. (Encyclopedia of World Biography)
	When Steinbeck was four years old he received his own pony named Jill. Jill became an inspiration for his future series of stories, The Red Pony. On his ninth birthday his Aunt Mollie gave him a copy of Le Morte d’Arthur.  This book inspired him to write Tortilla Flat which used Arthurian Tropes and chapter headings. He also traveled to England and Wales to research Arthurian legends in preparation for a modernized text of Arthurian tales. (Keith Ferrell, 82)
	During High School John showed strong interest in writing. He would work late into the night up in his attic and write short stories. Sometimes he would invite his friends over and read them aloud. John writes decades later, 'I would send in my little stories out to magazines under a false name and I never put a return address on them… I wonder what I was thinking of? I was scared to death to get a rejection slip, but more, to get an acceptance.' (John Steinbeck Biography) By the age of fourteen he was certain he wanted to become and Author.
	In 1919 he enrolled at Stanford University hoping to sharpen his writing skills. He took world history and creative writing courses, and in 1923 he enrolled in a biology course at Hopkins Marine Station. He left Stanford in 1925 without receiving a degree. (Galegroup)
	Some of Steinbeck’s major works were Of Mice and Men, The Grapes of Wrath, East of Eden, The Pearl, and Canary Row. His writings were very important to us because they shed some light on the Great Depression and the years surrounding it. He also talked a lot about the American Dream and realism. Most of his books were about the Great Depression, but some of his books, like Tortilla Flat, were about Arthurian tales.
	Steinbeck’s book, Of Mice and Men, was inspired by his growing up on a ranch himself. It shows how bad the ranchers lives were during the Great Depression, moving Ranch to Ranch just so they could stay alive. Ranchers barely made any friends because they were constantly moving from place to place. It also talks about the American Dream. In the book George and Lenny’s dream was to own their very own Ranch, so they wouldn’t need to constantly keep moving, and on the ranch they would have all kinds of animals, especially bunnies, for Lenny to play with.
	John Steinbeck died in New York City on December 20, 1968 of Heart disease and congestive heart failure. He had been a lifelong smoker, and his autopsy showed nearly complete occlusion of the main coronary arteries. He died at the age of 66, and according to his wishes, he was cremated and interred at the Hamilton Family Gravesite in Salinas.", 6);
INSERT INTO Blog (BlogTitle, BlogBody, AuthorID) VALUES ("This is a default Politics blog", "I don't really know what to enter here so I'm just going to keep typing random things until I feel it is long enough. I want to make this post really long so that we can format the page accordingly. I will also create a shorter blog post so we can test to see if that works with short blogs as well. I don't really know what else to type. I'm considering just copying an essay I have written for school so that this blog post is reallllly long.  Here is my essay about John Steinbeck (I Think this was from High school).
 	John Steinbeck was born on February 27, 1902 in Salinas, California. He was the third child of Olive Hamilton and John Ernst Steinbeck. He had two older sisters and a younger sister. Salinas was a farming community, and he wrote about it in 1952 in East of Eden. When John was in his youth his family went through many financial problems including his father losing his jab as manager of Sperry flour and having a grain store they own closed down. These problems continued until John went to college. (Encyclopedia of World Biography)
	When Steinbeck was four years old he received his own pony named Jill. Jill became an inspiration for his future series of stories, The Red Pony. On his ninth birthday his Aunt Mollie gave him a copy of Le Morte d’Arthur.  This book inspired him to write Tortilla Flat which used Arthurian Tropes and chapter headings. He also traveled to England and Wales to research Arthurian legends in preparation for a modernized text of Arthurian tales. (Keith Ferrell, 82)
	During High School John showed strong interest in writing. He would work late into the night up in his attic and write short stories. Sometimes he would invite his friends over and read them aloud. John writes decades later, 'I would send in my little stories out to magazines under a false name and I never put a return address on them… I wonder what I was thinking of? I was scared to death to get a rejection slip, but more, to get an acceptance.' (John Steinbeck Biography) By the age of fourteen he was certain he wanted to become and Author.
	In 1919 he enrolled at Stanford University hoping to sharpen his writing skills. He took world history and creative writing courses, and in 1923 he enrolled in a biology course at Hopkins Marine Station. He left Stanford in 1925 without receiving a degree. (Galegroup)
	Some of Steinbeck’s major works were Of Mice and Men, The Grapes of Wrath, East of Eden, The Pearl, and Canary Row. His writings were very important to us because they shed some light on the Great Depression and the years surrounding it. He also talked a lot about the American Dream and realism. Most of his books were about the Great Depression, but some of his books, like Tortilla Flat, were about Arthurian tales.
	Steinbeck’s book, Of Mice and Men, was inspired by his growing up on a ranch himself. It shows how bad the ranchers lives were during the Great Depression, moving Ranch to Ranch just so they could stay alive. Ranchers barely made any friends because they were constantly moving from place to place. It also talks about the American Dream. In the book George and Lenny’s dream was to own their very own Ranch, so they wouldn’t need to constantly keep moving, and on the ranch they would have all kinds of animals, especially bunnies, for Lenny to play with.
	John Steinbeck died in New York City on December 20, 1968 of Heart disease and congestive heart failure. He had been a lifelong smoker, and his autopsy showed nearly complete occlusion of the main coronary arteries. He died at the age of 66, and according to his wishes, he was cremated and interred at the Hamilton Family Gravesite in Salinas.", 6);
INSERT INTO Blog (BlogTitle, BlogBody, AuthorID) VALUES ("This is a default music blog", "This is a short music blog", 6);
INSERT INTO Blog (BlogTitle, BlogBody, AuthorID) VALUES ("This is a default Finance blog", "This is a short finance blog", 6);



INSERT INTO BlogToTag (BlogID, TagID) VALUES (1,1);
INSERT INTO BlogToTag (BlogID, TagID) VALUES (2,2);
INSERT INTO BlogToTag (BlogID, TagID) VALUES (3,3);
INSERT INTO BlogToTag (BlogID, TagID) VALUES (4,4);
INSERT INTO BlogToTag (BlogID, TagID) VALUES (5,5);


INSERT INTO Comment (BlogID, CommentBody, UserID) VALUES (1, "I LOVE SPORTS", 1);
INSERT INTO Comment (BlogID, CommentBody, UserID) VALUES (2, "I LOVE TECHNOLOGY",2);
INSERT INTO Comment (BlogID, CommentBody, UserID) VALUES (3, "I HATE POLITICS", 5);
INSERT INTO Comment (BlogID, CommentBody, UserID) VALUES (4, "I LOVE MUSIC", 1);
INSERT INTO Comment (BlogID, CommentBody, UserID) VALUES (5, "I HATE FINANCE", 2);
INSERT INTO Comment (BlogID, CommentBody, UserID) VALUES (1, "Soccer is my favorite", 5);
INSERT INTO Comment (BlogID, CommentBody, UserID) VALUES (1, "Basketball is better than soccer", 1);


INSERT INTO BlogToPermission (BlogID, PermissionID) VALUES (2,3);
INSERT INTO BlogToPermission (BlogID, PermissionID) VALUES (3,3);
INSERT INTO BlogToPermission (BlogID, PermissionID) VALUES (4,4);
INSERT INTO BlogToPermission (BlogID, PermissionID) VALUES (5,4);
